version: '3.7'

services:
  app:
    container_name: client-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - gerenciador-clientes

  nginx:
    container_name: client-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - gerenciador-clientes
    depends_on:
      - app
  
networks:
  gerenciador-clientes:
    driver: bridge